Client/Areas/Staff/Controllers/CategoryController.cs
using Api.Responses;
using Client.Helpers;
using Client.Requests;
using Client.Responses;
using Client.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using static Google.Apis.Requests.BatchRequest;

namespace Client.Areas.Mentor.Controllers
{
    [Area("Staff")]
    [Route("Staff/[Controller]/[Action]")]
    [Authorize(Roles = "Staff")]
    public class CategoryController : Controller
    {
        private readonly ClientService _clientService;
        public CategoryController(ClientService clientService)
        {
            _clientService = clientService;
        }

        [HttpGet]
        public async Task<IActionResult> Index(PagingRequest<CategoryResponse> request)
        {
            try
            {
                var response = await _clientService.Get<ODataResponseModel<CategoryResponse>>(ApiPaths.Categories);
                if (response == null) throw new Exception();
                var searchTerm = (request.SearchTerm ?? "").ToLower();
                var categories = response.Value;
                categories = categories
                    .Where(x => x.CategoryName.ToLower().Contains(searchTerm))
                    .ToList();
                request.TotalRecord = categories.Count;

                request.TotalPages = (int)Math.Ceiling(request.TotalRecord / (double)request.PageSize);
                categories = categories.Skip((request.CurrentPage - 1) * request.PageSize).Take(request.PageSize).ToList();
                request.Items = categories;
            }
            catch (Exception)
            {

            }
            return View(request);
        }

        [HttpGet]
        public async Task<IActionResult> GetCategoryById(int id)
        {
            try
            {
                var response = await _clientService.Get<CategoryResponse>(ApiPaths.Categories + "/" + id);
                if (response == null) throw new Exception("");
                return Ok(response);
            }
            catch (Exception ex)
            {
                return NotFound();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Create(CategoryRequest request)
        {
            try
            {
                if (!ModelState.IsValid) throw new Exception("Invalid category information.");

                var response = await _clientService.Post<ResponseModel>(ApiPaths.Categories, request);
                if (response == null || response?.Success == false) throw new Exception("Create category failed.");

                ToastHelper.ShowSuccess(TempData, "Create category successfully.");

            }
            catch (Exception ex)
            {
                ToastHelper.ShowError(TempData, ex.Message);
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> Update(CategoryRequest request)
        {
            try
            {
                if (!ModelState.IsValid) throw new Exception("Invalid category information.");
                var url = ApiPaths.Categories + "/" + request.CategoryId;
                var response = await _clientService.Put<ResponseModel>(url, request);
                if (response == null || response?.Success == false) throw new Exception("Update category failed.");

                ToastHelper.ShowSuccess(TempData, "Update category successfully.");

            }
            catch (Exception ex)
            {
                ToastHelper.ShowError(TempData, ex.Message);
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                var response = await _clientService.Delete<ResponseModel>(ApiPaths.Categories + "/" + id);
                if (response == null || response?.Success == false) throw new Exception("Cannot delete category because it is used.");

                ToastHelper.ShowSuccess(TempData, "Delete category successfully.");
            }
            catch (Exception ex)
            {
                ToastHelper.ShowWarning(TempData, ex.Message);
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

Client/Areas/Staff/Controllers/TagController.cs
using Api.Responses;
using Client.Helpers;
using Client.Requests;
using Client.Responses;
using Client.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Client.Areas.Staff.Controllers
{
    [Area("Staff")]
    [Route("Staff/[Controller]/[Action]")]
    [Authorize(Roles = "Staff")]
    public class TagController : Controller
    {
        private readonly ClientService _clientService;
        public TagController(ClientService clientService)
        {
            _clientService = clientService;
        }

        [HttpGet]
        public async Task<IActionResult> Index(PagingRequest<TagResponse> request)
        {
            try
            {
                var response = await _clientService.Get<ODataResponseModel<TagResponse>>(ApiPaths.Tags);
                if (response == null) throw new Exception();
                var searchTerm = (request.SearchTerm ?? "").ToLower();
                var categories = response.Value;
                categories = categories
                    .Where(x => x.TagName.ToLower().Contains(searchTerm))
                    .ToList();
                request.TotalRecord = categories.Count;

                request.TotalPages = (int)Math.Ceiling(request.TotalRecord / (double)request.PageSize);
                categories = categories.Skip((request.CurrentPage - 1) * request.PageSize).Take(request.PageSize).ToList();
                request.Items = categories;
            }
            catch (Exception)
            {

            }
            return View(request);
        }

        [HttpGet]
        public async Task<IActionResult> GetTagById(int id)
        {
            try
            {
                var response = await _clientService.Get<TagResponse>(ApiPaths.Tags + "/" + id);
                if (response == null) throw new Exception("");
                return Ok(response);
            }
            catch (Exception ex)
            {
                return NotFound();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Create(TagRequest request)
        {
            try
            {
                if (!ModelState.IsValid) throw new Exception("Invalid tag information.");

                var response = await _clientService.Post<ResponseModel>(ApiPaths.Tags, request);
                if (response == null || response?.Success == false) throw new Exception("Create tag failed.");

                ToastHelper.ShowSuccess(TempData, "Create tag successfully.");

            }
            catch (Exception ex)
            {
                ToastHelper.ShowError(TempData, ex.Message);
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> Update(TagRequest request)
        {
            try
            {
                if (!ModelState.IsValid) throw new Exception("Invalid tag information.");
                var url = ApiPaths.Tags + "/" + request.TagId;
                var response = await _clientService.Put<ResponseModel>(url, request);
                if (response == null || response?.Success == false) throw new Exception("Update tag failed.");

                ToastHelper.ShowSuccess(TempData, "Update tag successfully.");

            }
            catch (Exception ex)
            {
                ToastHelper.ShowError(TempData, ex.Message);
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                var response = await _clientService.Delete<ResponseModel>(ApiPaths.Tags + "/" + id);
                if (response == null || response?.Success == false) throw new Exception("Cannot delete tag because it is used.");

                ToastHelper.ShowSuccess(TempData, "Delete tag successfully.");
            }
            catch (Exception ex)
            {
                ToastHelper.ShowWarning(TempData, ex.Message);
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

Client/Controllers/AuthenController.cs
using Api.Responses;
using Client;
using Client.Constants;
using Client.Helpers;
using Client.Models;
using Client.Requests;
using Client.Responses;
using Client.Services;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication.Google;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Data;
using System.Security.Claims;
using static Google.Apis.Requests.BatchRequest;

namespace FCMS.Client.Controllers
{
    public class AuthenController : Controller
    {
        private readonly ClientService _clientService; 
        private readonly IConfiguration _configuration;

        public AuthenController(
            IConfiguration configuration,
            ClientService clientService
        )
        {
            _configuration = configuration;
            _clientService = clientService;
        }

        [HttpGet("SignIn")]
        public async Task<IActionResult> SignIn()
        {
            try
            {
                var userInfo = SessionHelper.GetObject<UserInfo>(HttpContext.Session, "UserInfo");

                if (userInfo != null)
                {
                    var role = (RoleEnum) userInfo.AccountRole;

                    switch (role)
                    {
                        case RoleEnum.Admin:
                            return RedirectToAction("Index", "Home", new { area = "Admin" });
                        case RoleEnum.Staff:
                            return RedirectToAction("Index", "Home", new { area = "Staff" });
                        default:
                            return View("Views/Home/Index.cshtml");
                    }
                }
            }
            catch (Exception ex)
            {
            }
            return View("Views/SignIn.cshtml");
        }

        [HttpPost("SignIn")]
        public async Task<IActionResult> SignIn(LoginRequest loginRequest)
        {
            try
            {
                if (!ModelState.IsValid) throw new Exception("Please enter your email and password.");
                var response = await _clientService.Post<ResponseModel>(ApiPaths.Login, loginRequest);

                if(response == null || response?.Message == null) throw new Exception("Email or password are not correct.");
                var accessToken = response?.Message;
                if (String.IsNullOrEmpty(accessToken))
                {
                    throw new Exception("Login failed.");
                }

                SessionHelper.SetObject(HttpContext.Session, "AccessToken", accessToken);
                var tokenHelper = new TokenHelper();
                var allClaims = tokenHelper.GetAllClaims(accessToken);

                var roleStr = tokenHelper.FindClaimValueByKey(allClaims, "Role");
                var accountRole = -1;
                int.TryParse(roleStr, out accountRole);

                var userInfo = new UserInfo();
                userInfo.AccountRole = accountRole; // Store the user's role integer
                userInfo.AccountName = tokenHelper.FindClaimValueByKey(allClaims, ClaimTypes.GivenName);
                userInfo.AccountEmail = tokenHelper.FindClaimValueByKey(allClaims, ClaimTypes.Email);
                userInfo.AccountId = int.Parse(tokenHelper.FindClaimValueByKey(allClaims, ClaimTypes.NameIdentifier));
                var role = (RoleEnum)userInfo.AccountRole;


                var claims = new List<Claim>
                {
                    new (ClaimTypes.Name, userInfo.AccountEmail),
                    new (ClaimTypes.Role, role == RoleEnum.Admin ? RoleName.Admin : RoleName.Staff) ,
                };

                var claimsIdentity = new ClaimsIdentity(claims, "SessionAuthenticationScheme");
                await HttpContext.SignInAsync("SessionAuthenticationScheme", new ClaimsPrincipal(claimsIdentity));

                SessionHelper.SetObject<UserInfo>(HttpContext.Session, "UserInfo", userInfo);
                ToastHelper.ShowSuccess(TempData, "Login successful.");

                // Redirect the user based on their role

                switch (role)
                {
                    case RoleEnum.Admin:
                        return RedirectToAction("Index", "Home", new { area = "Admin" });
                    case RoleEnum.Staff:
                        return RedirectToAction("Index", "Home", new { area = "Staff" });
                    default:
                        return View("Views/Home/Index.cshtml");
                }
            }
            catch (Exception ex)
            {
                ToastHelper.ShowError(TempData, ex.Message);
                return RedirectToAction(nameof(SignIn));
            }
        }

        [HttpGet("SignOut")]
        public async Task<IActionResult> SignOut()
        {
            try
            {
                SessionHelper.Remove(HttpContext.Session, "UserInfo");
                SessionHelper.Remove(HttpContext.Session, "AccessToken");

                await HttpContext.SignOutAsync("SessionAuthenticationScheme");
            }
            catch (Exception ex)
            {
                ToastHelper.ShowError(TempData, ex.Message);
            }
            return RedirectToAction("Index", "Home"); 
        }
    }
}

Client/Controllers/NewsController.cs
using Api.Responses;
using Client.Helpers;
using Client.Requests;
using Client.Responses;
using Client.Services;
using Microsoft.AspNetCore.Mvc;

namespace Client.Controllers
{
    public class NewsController : Controller
    {
        private readonly ClientService _clientService;
        public NewsController(ClientService clientService)
        {
            _clientService = clientService;
        }

        [HttpGet]
        public async Task<IActionResult> Index(NewsPagingRequest request)
        {
            try
            {
                var response = await _clientService.Get<ODataResponseModel<NewsResponse>>(ApiPaths.News);
                if (response == null) throw new Exception();
                var searchTerm = (request.SearchTerm ?? "").ToLower();
                var news = response.Value;
                news = news
                    .Where(x => x.NewsTitle.ToLower().Contains(searchTerm) || x.NewsContent.ToLower().Contains(searchTerm))
                    .Where(x => request.CategoryId != null && request.CategoryId != -1 ? x.CategoryId == request.CategoryId : true)
                    .ToList();
                request.TotalRecord = news.Count;

                request.TotalPages = (int)Math.Ceiling(request.TotalRecord / (double)request.PageSize);
                news = news.Skip((request.CurrentPage - 1) * request.PageSize).Take(request.PageSize).ToList();               
                request.Items = news;

                var categories = await _clientService.Get<ODataResponseModel<CategoryResponse>>(ApiPaths.Categories);
                var tags = await _clientService.Get<ODataResponseModel<TagResponse>>(ApiPaths.Tags);

                ViewBag.Categories = categories.Value;
                ViewBag.Tags = tags.Value;

            }
            catch (Exception)
            {

            }
            return View(request);
        }

        [HttpGet]
        public async Task<IActionResult> Details(string id)
        {
            try
            {
                var news = await _clientService.Get<ODataResponseModel<NewsResponse>>(ApiPaths.News);
                var response = await _clientService.Get<NewsResponse>(ApiPaths.News + "/" + id);
                var categories = await _clientService.Get<ODataResponseModel<CategoryResponse>>(ApiPaths.Categories);
                var tags = await _clientService.Get<ODataResponseModel<TagResponse>>(ApiPaths.Tags);
                ViewBag.Categories = categories.Value;
                ViewBag.Tags = tags.Value;
                ViewBag.RelatedNews = news.Value.Take(5).ToList();

                if (response == null) throw new Exception();
                return View(response);
            }
            catch (Exception ex)
            {
                ToastHelper.ShowError(TempData, "Cannot find the news.");
                return RedirectToAction(nameof(Index));
            }
        }
    }
}

Client/Views/Shared/Layouts/_Layout.cshtml
@using Client.Services
@using Client.Helpers
@{

    var currentController = ViewContext.RouteData.Values["controller"] as string;
    var currentAction = ViewContext.RouteData.Values["action"] as string;

}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@currentController | CMCS</title>
    <link rel="icon" href="~/icon.png" type="image/x-icon" />
    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet"
          crossorigin="anonymous">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/lib/bootstrap-select/css/bootstrap-select.min.css" />

    <link rel="stylesheet" href="~/css/shared.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/guest-site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/variables.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/toast.css" asp-append-version="true" />

    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/lib/bootstrap-select/js/bootstrap-select.min.js"></script>
</head>

<body>
    <!-- ======= Header ======= -->
    <header id="header" class="header fixed-top">
        <div class="container-fluid d-flex align-items-center justify-content-between">

            <a asp-controller="Home" asp-action="Index" class="logo d-flex align-items-center scrollto me-auto me-lg-0">
                <img src="/assets/images/fpt-education-logo.png" />
            </a>
            <nav id="navbar" class="navbar">
                <ul>
                    <li class="nav-item " title="Home">
                        <a asp-controller="Home" asp-action="Index" class="nav-link @(currentController == "Home" && currentAction == "Index" ? "active" : "")">
                            Home
                        </a>
                    </li><!-- End Home Nav -->

                    <li class="nav-item " title="Sự kiện">
                        <a asp-controller="News" asp-action="Index" class="nav-link @(currentController == "News" ? "active" : "")">
                            News
                        </a>
                    </li>
                </ul>

            </nav><!-- navbar -->
            <div class="navbar-mobile" style="display: contents;">
                <a class="mobile-nav-toggle d-none" href="#" data-bs-toggle="dropdown">
                    <i class="bi bi-list "></i>
                </a><!-- End Profile Iamge Icon -->
                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow ">
                    <li class="nav-item " title="Trang chủ">
                        <a asp-controller="Home" asp-action="Index" class="nav-link @(currentController == "Home" && currentAction == "Index" ? "active" : "")">
                            Home
                        </a>
                    </li><!-- End Home Nav -->

                    <li class="nav-item " title="Sự kiện">
                        <a asp-controller="Event" asp-action="Index" class="nav-link @(currentController == "News" ? "active" : "")">
                            News
                        </a>
                    </li><!-- End Events Nav -->
                    <li class="nav-item" title="Liên hệ">
                        <a asp-controller="Contact" asp-action="Index" class="nav-link @(currentController == "Contact"  ? "active" : "")">
                            Contact
                        </a>
                    </li><!-- End Clubs Nav -->
                    <li class="nav-item px-3 py-2" title="Đăng nhập">
                        <a class="btn btn-primary btn-signin nav-link color-white py-2" asp-controller="Authen" asp-action="SignIn">Login</a>
                    </li><!-- End Clubs Nav -->

                </ul><!-- End Profile Dropdown Items -->

            </div>

            <a class="btn btn-primary btn-signin" asp-controller="Authen" asp-action="SignIn">Login</a>

        </div>
    </header><!-- End Header -->

    <main id="main" class="main ">
        @RenderBody()
    </main><!-- End #main -->
    <!-- ======= Footer ======= -->
    <footer id="footer" class="footer">

        <div class="footer-content">
            <div class="container">
                <div class="copyright text-center">
                    &copy; Copyright <strong><span>FPT Education</span></strong>
                </div>
            </div>
        </div>


    </footer><!-- End Footer -->

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/toast.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <script>
        toastr.options = {
            "closeButton": true,
            "debug": false,
            "newestOnTop": true,
            "progressBar": true,
            "positionClass": "toast-bottom-right",
            "preventDuplicates": false,
            "onclick": null,
            "showDuration": "200",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }

        $(function () {

            var toastMessage = '@TempData["ToastMessage"]';
            var toastType = '@TempData["ToastType"]';
            if (toastMessage && toastType) {
                toastr[toastType](toastMessage);
            }
        });



    </script>
</body>
</html>

Client/Views/Shared/Layouts/_StaffLayout.cshtml
@using Client.Services
@using Client.Helpers
@using Client.Models
@{
    var userInfo = SessionHelper.GetObject<UserInfo>(Context.Session, "UserInfo");

    var currentController = ViewContext.RouteData.Values["controller"] as string;
    var currentAction = ViewContext.RouteData.Values["action"] as string;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@currentController | CMCS</title>
    <link rel="icon" href="~/icon.png" type="image/x-icon" />
    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet"
          crossorigin="anonymous">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/lib/bootstrap-select/css/bootstrap-select.min.css" />

    <link rel="stylesheet" href="~/css/shared.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/variables.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/toast.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/lib/bootstrap-select/js/bootstrap-select.min.js"></script>
  
</head>
<body>
    <header id="header" class="header fixed-top d-flex align-items-center">

        <div class="d-flex align-items-center justify-content-between">
            <a asp-controller="Home" asp-action="Index" class="logo d-flex align-items-center ">
                <img src="/assets/images/fpt-education-logo.png" alt="">
            </a>
        </div><!-- End Logo -->
        <nav class="header-nav-on-phone ms-auto mx-3">

            <a class="nav-profile" href="#" data-bs-toggle="dropdown">
                <div class="center">
                    <div class="avatar">
                        <img src="/assets/images/user-default-avatar.png" alt="Profile" class="rounded-circle">
                    </div>
                    <span class="fs-6 ms-1">@userInfo.AccountName</span>

                </div>
            </a><!-- End Profile Iamge Icon -->
            <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
                <li class="dropdown-header">
                    <h6>@userInfo.AccountName</h6>
                    <span>Staff</span>
                </li>

                <li>
                    <hr class="dropdown-divider">
                </li>

                <li>
                    <a asp-area="Staff" asp-controller="Profile" asp-action="Update" class="dropdown-item d-flex align-items-center  @(currentController == "Profile" ? "active" : "")">
                        <i class="bi bi-person"></i>
                        <span>Profile</span>
                    </a>
                </li>

                <li>
                    <hr class="dropdown-divider">
                </li>

                <li>
                    <a asp-controller="Authen" asp-action="SignOut" class="dropdown-item d-flex align-items-center">
                        <i class="bi bi-box-arrow-right"></i>
                        <span>Sign out</span>
                    </a>
                </li>

            </ul><!-- End Profile Dropdown Items -->
        </nav><!-- End Icons Navigation -->
    </header><!-- End Header -->
    <!-- ======= Sidebar ======= -->
    <aside id="sidebar" class="sidebar">
        <ul class="sidebar-nav" id="sidebar-nav">

            <li class="nav-item">
                <a asp-area="Staff" asp-controller="Home" asp-action="Index" class="nav-link @(currentController == "Home" && currentAction == "Index" ? "" : "collapsed")">
                    <i class="bi bi-house-door"></i>
                    <span>Dashboard</span>
                </a>
            </li><!-- End Home Nav -->


            <li class="nav-item">
                <a asp-area="Staff" asp-controller="News" asp-action="Index" class="nav-link @(currentController == "News"  ? "" : "collapsed")">
                    <i class="bi bi-calendar-event"></i><span>Manage News</span>
                </a>
            </li><!-- End Home Nav -->
            
            <li class="nav-item">
                <a asp-area="Staff" asp-controller="Category" asp-action="Index" class="nav-link @(currentController == "Category" ? "" : "collapsed")">
                    <i class="bi bi-card-text"></i>
                    <span>Manage Category</span>
                </a>
            </li><!-- End Home Nav -->

            <li class="nav-item">
                <a asp-area="Staff" asp-controller="Tag" asp-action="Index" class="nav-link @(currentController == "Tag"  ? "" : "collapsed")">
                    <i class="bi bi-fire"></i>
                    <span>Manage Tag</span>
                </a>
            </li><!-- End Notification Nav -->
        </ul>
    </aside>

    <!-- End Sidebar-->
    <img id="toggle-sidebar-btn" src="/assets/icons/toggle-sidebar-btn.svg" class="toggle-sidebar-btn" />

    <main id="main" class="main">
        @RenderBody()
    </main><!-- End #main -->
    <!-- ======= Footer ======= -->
    <footer id="footer" class="footer">
        <div class="w-100 text-center">
            &copy; Copyright <strong><a class="copyright text-center" href="#">FPT Education</a></strong>
        </div>

    </footer><!-- End Footer -->

    <div id="loader" class="loader-container" style="display: none;">
        <div class="spinner-border text-primary m-auto" role="status">
            <span class="visually-hidden">Loading...</span>
        </div>
    </div>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/maxlength.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/toast.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

    <script>
        toastr.options = {
            "closeButton": true,
            "debug": false,
            "newestOnTop": true,
            "progressBar": true,
            "positionClass": "toast-bottom-right",
            "preventDuplicates": false,
            "onclick": null,
            "showDuration": "200",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }

        $(function () {

            var toastMessage = '@TempData["ToastMessage"]';
            var toastType = '@TempData["ToastType"]';
            if (toastMessage && toastType) {
                toastr[toastType](toastMessage);
            }
        });

    </script>
</body>
</html>